# Generated by Django 4.1.6 on 2023-02-09 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_ingredients'),
        ('ingredients', '0003_alter_ingredient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='name',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amount_required',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measure_unit',
            field=models.CharField(choices=[('cup', 'cup(s)'), ('g', 'gram'), ('tablespoon', 'tablespoon(s)'), ('item', 'item'), ('ml', 'ml'), ('l', 'L'), ('kg', 'kg'), ('ounce', 'ounce')], default='g', max_length=25),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ingredient_needed',
        ),
    ]
