# Generated by Django 4.1.6 on 2023-02-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_remove_ingredient_name_ingredient_amount_required_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient',
            new_name='name',
        ),
    ]
