# Generated by Django 4.1.6 on 2023-02-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_ingredients'),
        ('ingredients', '0006_ingredient_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'recipe')},
        ),
    ]
