# Generated by Django 4.1.6 on 2023-02-08 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('category', models.CharField(choices=[('starter', 'Starter'), ('main', 'Main'), ('dessert', 'Dessert'), ('snack', 'Snack')], default='main', max_length=30)),
                ('cooking_time', models.IntegerField()),
                ('prep_time', models.IntegerField()),
                ('image', models.ImageField(blank=True, default='../rachel-park-hrlvr2ZlUNk-unsplash_eseqep', upload_to='images/')),
                ('ingredients', models.ManyToManyField(related_name='recipes', through='ingredients.Ingredient_needed', to='ingredients.ingredient')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
