# Generated by Django 3.2.4 on 2023-02-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='../rachel-park-hrlvr2ZlUNk-unsplash_eseqep.jpg', upload_to='images/'),
        ),
    ]
